# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwtn', '0002_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#990000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='pin',
            field=models.CharField(default='assets/pin.png', max_length=200),
            preserve_default=False,
        ),
    ]
